# Kotaemon 🤖, Apache-2.0 license

name: "🐞 Bug Report"
description: "Problems with Kotaemon"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Kotaemon 🐞 Bug Report!
        
  - type: checkboxes
    attributes:
      label:  "Search before asking"
      description: >
        Kindly look up the Kotaemon [issues](https://github.com/Cinnamon/kotaemon/issues) to see if any similar bug report already exists.
      options: 
      - label: >
          I have looked up the issue pool and found no similar bug report!
        required: true

  - type: dropdown
    attributes:
      label: "Kotaemon component"
      description: "Please select the Kotaemon component where you found the bug."
      multiple: true
      options:
        - "Setup Script"
        - "UI"
        - "Readers (file loaders)"
        - "GraphRAG Integration"
        - "File Management"
        - "LLM & Embedding Models (Incl local LLMs)"
        - "Docker build & CI/CD"
        - "Others"
      validations:
        required: true

  - type: textarea
    attributes:
      label: "Bug Description"
      description: "Please provide as much information as possible. Copy and paste console output and error messages. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only (You can also copy and paste into the box). Providing detailed information will help us resolve the issue more efficiently."
      placeholder: |
        🤝 Pro Tip! To get the most helpful response, include as much information as possible (e.g., logs, tracebacks, screenshots, etc.)
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "When filing a bug, you’ll get better help if you provide clear, understandable code or steps that others can use to reproduce the problem."
      placeholder: |
        ```
        # Code or steps to reproduce your issue here
        ```
      render: bash
    validations:
      required: true
    
#  - type: textarea
#    id: screenshot
#    attributes:
#      label: "Screenshots"
#      description: If applicable, add screenshots to help explain your problem.
#      value: |
#        ![DESCRIPTION](LINK.png)
#      render: bash
#    validations:
#      required: false
 
#  - type: textarea
#    id: logs
#    attributes:
#      label: "Logs"
#      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
#      render: bash
#    validations:
#      required: false
      
  - type: dropdown
    attributes:
      label: "Browsers"
      description: "Which browsers are you using when you see the problem?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Brave
        - Other
    validations:
      required: false
      
  - type: dropdown
    attributes:
      label: "OS"
      description: "What is the impacted environment?"
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: "Remark"
      description: Is there anything else you would like to share?
    validations:
      required: false
